--1.
SELECT STUDENT_NO 학번,STUDENT_NAME 이름 ,ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE NOT PROFESSOR_NAME LIKE ('___');

--3.
SELECT PROFESSOR_NAME 교수이름, 100 - SUBSTR(PROFESSOR_SSN,1,2)+ 25 나이
FROM TB_PROFESSOR
ORDER BY 100 - SUBSTR(PROFESSOR_SSN,1,2)+ 25;

--4.
SELECT SUBSTR(PROFESSOR_NAME,2,2)
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
WHERE 100 - SUBSTR(STUDENT_SSN,1,2) + SUBSTR(ENTRANCE_DATE,3,2) > 19;