--1.
SELECT STUDENT_NO 학번,STUDENT_NAME 이름 ,ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE NOT PROFESSOR_NAME LIKE ('___');

--3.
SELECT PROFESSOR_NAME 교수이름, 100 - SUBSTR(PROFESSOR_SSN,1,2)+ 25 나이
FROM TB_PROFESSOR
ORDER BY 100 - SUBSTR(PROFESSOR_SSN,1,2)+ 25;

--4.
SELECT SUBSTR(PROFESSOR_NAME,2,2)
FROM TB_PROFESSOR;

--5.
SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
WHERE 100 - SUBSTR(STUDENT_SSN,1,2) + SUBSTR(ENTRANCE_DATE,3,2) > 19;

--6.
SELECT TO_CHAR(TO_DATE('2020-12-25', 'YYYY-MM-DD'), 'DAY')
FROM DUAL;

--7.
--SELECT TO_DATE('99/10/11','YY/MM/DD')
--FROM DUAL;

--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A'
ORDER BY STUDENT_NO DESC;

--9.
SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO 학과번호, COUNT(*)"학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;
--dd
--12.
SELECT SUBSTR(TERM_NO,1,4)"년도",POINT"년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';

--13.
SELECT DEPARTMENT_NO 학과코드명, 
      COUNT(*) "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--14.
SELECT STUDENT_NAME 동일이름, COUNT(*)"동일인 수"
FROM TB_STUDENT
HAVING COUNT(*) > 1
GROUP BY STUDENT_NAME
ORDER BY STUDENT_NAME;

--15.
SELECT SUBSTR(TERM_NO,1,4)년도, SUBSTR(TERM_NO,5,2)학기,POINT 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';