--1
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2.
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY SUBSTR(STUDENT_SSN,1,2) DESC, SUBSTR(STUDENT_SSN,3,2) DESC;

--3.
SELECT STUDENT_NAME 학생이름, DEPARTMENT_NO 학번, STUDENT_ADDRESS"거주지 주소"
FROM TB_STUDENT
WHERE (SUBSTR(STUDENT_ADDRESS,1,3) = '강원도' OR SUBSTR(STUDENT_ADDRESS,1,3) = '경기도')
AND SUBSTR(STUDENT_NO,1,2) = '99'
ORDER BY STUDENT_NAME;

--4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR P ,TB_DEPARTMENT D
WHERE P.DEPARTMENT_NO = D.DEPARTMENT_NO
AND P.DEPARTMENT_NO = '005'
ORDER BY SUBSTR(PROFESSOR_SSN,1,2); 

--5.


